CREATE TABLE IF NOT EXISTS maintenance_modes (
  maintenance_mode_id INT AUTO_INCREMENT PRIMARY KEY,
  scope_type VARCHAR(20) NOT NULL,
  building_id INT DEFAULT NULL,
  zone_id INT DEFAULT NULL,
  device_id INT DEFAULT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  reason TEXT,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ends_at TIMESTAMP NULL DEFAULT NULL,
  created_by VARCHAR(120),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (building_id) REFERENCES buildings(building_id) ON DELETE CASCADE,
  FOREIGN KEY (zone_id) REFERENCES zones(zone_id) ON DELETE CASCADE,
  FOREIGN KEY (device_id) REFERENCES devices(device_id) ON DELETE CASCADE
);
