CREATE TABLE IF NOT EXISTS feature_flags (
  feature_key VARCHAR(80) PRIMARY KEY,
  label VARCHAR(160) NOT NULL,
  description TEXT,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
