input {
  gelf {
    port => 12201
  }
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => {
      "platform" => "bems"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bems-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
