#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

required_files=(
  "docs/architecture.md"
  "docs/api-surface.md"
  "docs/bacnet-135-2020-conformance.md"
  "docs/bacnet-ecostruxure-system-diagram.md"
  "docs/bems-backend-design.md"
  "docs/device-architecture.md"
  "docs/database-schema.md"
  "docs/product-overview.md"
  "docs/SDD.docx"
  "docs/SDP.docx"
  "docs/generate_enterprise_docs.py"
  "database/schema.sql"
  "docker/docker-compose.yml"
  "docker/monitoring/prometheus.yml"
  "docker/monitoring/alerts.yml"
  "docker/monitoring/alertmanager.yml"
  "docker/monitoring/grafana/dashboards/bems-overview.json"
  "docker/logging/logstash/pipeline/bems.conf"
  "docker/init/schema.sql"
  "edge-core/Dockerfile"
  "edge-core/src/edge_grpc_server.cpp"
  "edge-core/src/edge_grpc_server.h"
  "edge-core/packaging/bems-edge-core.service"
  "edge-core/src/bacnet_interface.cpp"
  "edge-core/src/modbus_rtu_interface.cpp"
  "edge-core/src/canbus_interface.cpp"
  "edge-core/src/fieldbus_gateway.cpp"
  "edge-core/src/edge_runtime.cpp"
  "edge-core/src/hvac_control.cpp"
  "edge-core/src/hvac_control.h"
  "edge-core/src/writeback_controller.cpp"
  "edge-core/tests/writeback_controller_test.cpp"
  "field-device/CMakeLists.txt"
  "field-device/README.md"
  "field-device/include/field_device_firmware.h"
  "field-device/src/field_device_firmware.cpp"
  "field-device/src/simulated_drivers.cpp"
  "field-device/src/simulated_drivers.h"
  "field-device/src/main.cpp"
  "field-device/tests/field_device_simulator_test.cpp"
  "edge-core/tests/bacnet_simulator_test.cpp"
  "edge-core/tests/fieldbus_interface_test.cpp"
  "edge-core/tests/energy_ai_test.cpp"
  "edge-core/tests/discovery_service_test.cpp"
  "edge-core/tests/hvac_control_test.cpp"
  "node-api/server.js"
  "node-api/auth.js"
  "node-api/eventBus.js"
  "node-api/tests/auth.test.js"
  "node-api/aiClient.js"
  "node-api/edgeClient.js"
  "node-api/migrations/001_enterprise_saas.sql"
  "node-api/migrations/002_user_authorization.sql"
  "node-api/migrations/003_ai_fdd_maintenance.sql"
  "node-api/migrations/004_floors_rooms.sql"
  "node-api/migrations/005_sample_floor_room_mapping.sql"
  "node-api/migrations/006_schedule_recurrence_overrides.sql"
  "node-api/migrations/007_maintenance_modes.sql"
  "node-api/migrations/008_alarm_logs.sql"
  "node-api/migrations/009_holidays_special_events.sql"
  "node-api/migrations/010_trend_logging.sql"
  "node-api/migrations/011_notification_outbox.sql"
  "node-api/migrations/012_feature_flags.sql"
  "node-api/migrations/013_remove_api_keys.sql"
  ".github/workflows/cd.yml"
  "scripts/backup_mysql.sh"
  "scripts/start_demo.sh"
  "scripts/restore_mysql.sh"
  "scripts/deploy_canary.sh"
  "scripts/promote_canary.sh"
  "scripts/rollback_canary.sh"
  "proto/ai_service.proto"
  "proto/edge_service.proto"
  "ai-service/app.py"
  "ai-service/test_app.py"
  "ui/src/App.jsx"
  "yocto/README.md"
)

for file in "${required_files[@]}"; do
  test -f "$file" || {
    echo "Missing required architecture file: $file" >&2
    exit 1
  }
done

checks=(
  "node-api/server.js:/api/v1/status"
  "node-api/server.js:/api/v1/auth/login"
  "node-api/server.js:/api/v1/auth/context"
  "node-api/auth.js:/api/v1/auth/context"
  "node-api/server.js:/api/buildings/:buildingId/floors"
  "node-api/server.js:/api/floors/:floorId/rooms"
  "node-api/server.js:/api/rooms/:roomId/zones"
  "node-api/server.js:/api/schedules/effective"
  "node-api/server.js:/api/holiday-schedules"
  "node-api/server.js:/api/special-events"
  "node-api/server.js:/api/edge/subscribe-cov"
  "node-api/server.js:/api/edge/capabilities"
  "node-api/server.js:EDGE_COMMAND_TRANSPORT"
  "node-api/server.js:queueEdgeCommand"
  "node-api/server.js:/api/edge/commands"
  "node-api/server.js:/api/edge/command-transport"
  "node-api/server.js:/api/edge/read-points-batch"
  "node-api/server.js:/api/edge/cov-notifications"
  "node-api/server.js:ConfirmedCOVNotification"
  "node-api/server.js:bems.edge.commands"
  "node-api/server.js:nrf52840.ota_update"
  "node-api/server.js:MQTT_BROKER_URL"
  "node-api/server.js:AZURE_IOT_HUB_HOSTNAME"
  "node-api/server.js:AWS_IOT_ENDPOINT"
  "node-api/server.js:nrf52840_bacnet_devices"
  "node-api/server.js:nRF52840 BACnet devices over wireless or wired field transport"
  "node-api/server.js:field_selectable_power_meter"
  "node-api/server.js:device_persistent_storage"
  "node-api/server.js:BACnet/IPv6"
  "node-api/server.js:Modbus TCP"
  "node-api/server.js:EIA-485"
  "node-api/server.js:Node-RED"
  "node-api/server.js:Sedona Function Blocks"
  "node-api/server.js:multi_protocol_translation"
  "node-api/server.js:/api/maintenance/modes"
  "node-api/server.js:maintenanceModeActiveSql"
  "node-api/server.js:maintenanceScopeFromTargets"
  "node-api/server.js:scheduleScopeFromTargets"
  "node-api/server.js:normalizeRecurrence"
  "node-api/server.js:/api/telemetry/stream"
  "node-api/server.js:/api/alarms/stream"
  "node-api/server.js:/api/alarm-logs"
  "node-api/server.js:logAlarmEvent"
  "node-api/server.js:/api/energy-services/esi"
  "node-api/server.js:/api/energy-services/signals"
  "node-api/server.js:/api/energy-services/bws"
  "node-api/server.js:/api/ai/reinforcement/policy"
  "node-api/server.js:/api/ai/weather-pricing"
  "node-api/server.js:/api/ai/smart-grid"
  "node-api/server.js:/api/ai/demand-response"
  "node-api/server.js:/api/ai/temperature-trends"
  "node-api/server.js:/api/ai/airflow-graph"
  "node-api/server.js:/api/ai/optimize-operation"
  "node-api/server.js:/api/ai/predictive-simulation"
  "node-api/server.js:/api/ai/control/iterate"
  "node-api/server.js:runControlLoopIteration"
  "node-api/server.js:buildGlobalState"
  "node-api/server.js:buildAirflowGraphModel"
  "node-api/server.js:/api/fdd/analyze"
  "node-api/server.js:/api/maintenance/tickets"
  "node-api/server.js:/api/bacnet/object-map"
  "node-api/server.js:/api/bacnet/equipment-map"
  "node-api/server.js:/api/bacnet/vendor-metadata"
  "node-api/server.js:/api/bacnet/mstp/read"
  "node-api/server.js:/api/bacnet/mstp/write"
  "node-api/server.js:buildBacnetMstpFrame"
  "node-api/server.js:bacnetMstpHeaderCrc"
  "node-api/server.js:buildBacnetObjectMap"
  "node-api/server.js:buildBacnetEquipmentMap"
  "node-api/server.js:buildBacnetVendorMetadata"
  "node-api/server.js:/api/trends"
  "node-api/server.js:/api/reports/summary"
  "node-api/server.js:/api/reports/heat-map"
  "node-api/server.js:/api/reports/export"
  "node-api/server.js:/api/reports/schedules"
  "node-api/server.js:/api/reports/schedule-runs"
  "node-api/server.js:/api/reports/schedules/run-due"
  "node-api/server.js:/api/reports/trends.csv"
  "node-api/server.js:/api/reports/energy.pdf"
  "node-api/server.js:/api/firmware/artifacts"
  "node-api/server.js:/api/firmware/ota-jobs"
  "node-api/server.js:signFirmwareManifest"
  "node-api/server.js:OTA_PRIVATE_KEY_PEM"
  "node-api/server.js:executeReportSchedule"
  "node-api/server.js:reports:manage"
  "node-api/server.js:escapeCsvValue"
  "node-api/server.js:/api/events/status"
  "node-api/server.js:buildEventDrivenArchitecture"
  "node-api/server.js:event_driven_architecture"
  "node-api/server.js:domain_event_publication"
  "node-api/server.js:persistTrendSnapshot"
  "node-api/server.js:buildSmartGridAiContext"
  "node-api/server.js:requirePermission"
  "node-api/auth.js:hashPassword"
  "node-api/auth.js:verifyPassword"
  "node-api/auth.js:X-Session-Token"
  "node-api/aiClient.js:AiOptimizationService"
  "node-api/edgeClient.js:EdgeCoreService"
  "docker/docker-compose.yml:EDGE_GRPC_ENDPOINT"
  "docker/docker-compose.yml:EDGE_COMMAND_TRANSPORT"
  "docker/docker-compose.yml:edge-core:50051"
  "docker/docker-compose.yml:BACNET_SIMULATOR_ENABLED"
  "node-api/Dockerfile:FROM ubuntu:22.04"
  "ui/Dockerfile:FROM ubuntu:22.04"
  "ai-service/Dockerfile:FROM ubuntu:22.04"
  "edge-core/Dockerfile:FROM ubuntu:22.04"
  "edge-core/Dockerfile:libprotobuf-dev"
  ".github/workflows/ci.yml:libprotobuf-dev"
  ".github/workflows/ci.yml:Configure C++ field device firmware"
  ".github/workflows/ci.yml:Test C++ field device firmware"
  "edge-core/src/edge_grpc_server.cpp:EdgeCoreService::Service"
  "edge-core/src/edge_grpc_server.cpp:runEdgeGrpcServer"
  "edge-core/src/main.cpp:EDGE_GRPC_BIND"
  "edge-core/packaging/bems-edge-core.service:EDGE_GRPC_BIND"
  "edge-core/packaging/bems-edge-core.service:BACNET_SIMULATOR_ENABLED=false"
  "edge-core/src/bacnet_interface.cpp:BACNET_SIMULATOR_ENABLED"
  "edge-core/src/bacnet_interface.cpp:SIM Floor 1 VAV Damper"
  "edge-core/tests/bacnet_simulator_test.cpp:bacnet_discover_device"
  "edge-core/tests/bacnet_simulator_test.cpp:bacnet_read_properties_multiple"
  "edge-core/tests/bacnet_simulator_test.cpp:bacnet_poll_cov_notification"
  "yocto/meta-bems/recipes-bems/edge-core/edge-core.bb:grpc"
  "ai-service/app.py:AiOptimizationService"
  "proto/ai_service.proto:service AiOptimizationService"
  "proto/edge_service.proto:service EdgeCoreService"
  "proto/edge_service.proto:SubscribeCov"
  "edge-core/src/bacnet_interface.cpp:Who-Is"
  "edge-core/src/bacnet_interface.cpp:ReadProperty"
  "edge-core/src/bacnet_interface.cpp:ReadPropertyMultiple"
  "edge-core/src/bacnet_interface.cpp:bacnet_read_properties_multiple"
  "edge-core/src/bacnet_interface.cpp:WriteProperty"
  "edge-core/src/bacnet_interface.cpp:SubscribeCOV"
  "edge-core/src/bacnet_interface.cpp:ConfirmedCOVNotification"
  "edge-core/src/bacnet_interface.cpp:UnconfirmedCOVNotification"
  "edge-core/src/bacnet_interface.cpp:bacnet_poll_cov_notification"
  "edge-core/README.md:sourceforge.net/projects/bacnet"
  "edge-core/src/modbus_rtu_interface.cpp:modbus_crc16"
  "edge-core/src/canbus_interface.cpp:canbus_validate_frame"
  "edge-core/src/fieldbus_gateway.cpp:SimulatorFieldbusGateway"
  "edge-core/src/fieldbus_gateway.h:IFieldbusGateway"
  "edge-core/tests/fieldbus_interface_test.cpp:testFieldbusGatewayFacade"
  "edge-core/src/fieldbus_gateway.cpp:readBacnetMstpPresentValue"
  "edge-core/src/fieldbus_gateway.cpp:writeBacnetMstpPresentValue"
  "edge-core/tests/fieldbus_interface_test.cpp:readBacnetMstpPresentValue"
  "edge-core/tests/energy_ai_test.cpp:testOptimizationRecommendations"
  "edge-core/tests/discovery_service_test.cpp:FakeDiscoveryClient"
  "edge-core/src/hvac_control.h:IHvacControlStrategy"
  "edge-core/src/hvac_control.cpp:PidController"
  "edge-core/tests/hvac_control_test.cpp:Chiller"
  "node-api/server.js:/api/modbus/rtu/read"
  "node-api/server.js:/api/canbus/send"
  "edge-core/src/bacnet_interface.cpp:schedule"
  "edge-core/tests/bacnet_simulator_test.cpp:bacnet_subscribe_cov"
  "edge-core/tests/bacnet_simulator_test.cpp:250"
  "edge-core/tests/writeback_controller_test.cpp:SafeWritebackController"
  "node-api/tests/auth.test.js:hashPassword"
  "ai-service/test_app.py:test_optimize_hydrates_persisted_policy"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS organizations"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS floors"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS rooms"
  "database/schema.sql:override_priority"
  "database/schema.sql:recurrence"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS user_sessions"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS audit_events"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS rl_q_values"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS fdd_findings"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS maintenance_tickets"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS maintenance_modes"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS alarm_logs"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS trend_logs"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS holiday_schedules"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS special_events"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS firmware_artifacts"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS report_schedules"
  "database/schema.sql:CREATE TABLE IF NOT EXISTS report_schedule_runs"
  "docker/init/schema.sql:CREATE TABLE IF NOT EXISTS firmware_artifacts"
  "docker/init/schema.sql:CREATE TABLE IF NOT EXISTS report_schedule_runs"
  "database/schema.sql:nRF52840 Lobby Temp BACnet Device"
  "database/schema.sql:Main Switchboard 5-in-1 Power Meter"
  "node-api/migrations/014_nrf52840_wireless_devices.sql:nRF52840 Wired Occupancy BACnet Device"
  "node-api/migrations/018_nrf52840_bacnet_devices.sql:bacnetDevice"
  "node-api/migrations/015_field_selectable_power_meter.sql:fieldSelectableProtocols"
  "node-api/migrations/016_eeprom_setpoint_storage.sql:eepromWritePolicy"
  "node-api/migrations/017_device_persistent_storage.sql:persistentStorage"
  "node-api/migrations/017_device_persistent_storage.sql:schedule"
  "node-api/migrations/019_bacnet_device_resident_schedules.sql:bacnetScheduleStorage"
  "node-api/migrations/020_device_battery_percentage.sql:batteryPercent"
  "node-api/migrations/021_ota_reporting_workflows.sql:firmware_artifacts"
  "node-api/migrations/021_ota_reporting_workflows.sql:report_schedules"
  "node-api/migrations/021_ota_reporting_workflows.sql:report_exports"
  "node-api/migrations/022_report_schedule_execution.sql:report_schedule_runs"
  "node-api/migrations/022_report_schedule_execution.sql:next_run_at"
  "node-api/server.js:syncDeviceResidentSchedules"
  "node-api/server.js:bacnet_device_resident_schedules"
  "node-api/server.js:bacnetScheduleStorage"
  "node-api/server.js:/api/devices/:deviceId/ota-update"
  "node-api/server.js:ota_firmware_update"
  "node-api/server.js:bacnet_bare_metal_field_devices"
  "node-api/server.js:SOLID"
  "node-api/server.js:Dependency Injection"
  "ui/src/App.jsx:LoginPage"
  "ui/src/App.jsx:Building Login"
  "ui/src/App.jsx:loginContext"
  "ui/src/App.jsx:getBuildingZones"
  "ui/src/App.jsx:formatZonePath"
  "ui/src/App.jsx:createSchedule"
  "ui/src/App.jsx:scheduleForm"
  "ui/src/App.jsx:holidaySchedules"
  "ui/src/App.jsx:specialEvents"
  "ui/src/App.jsx:createHolidaySchedule"
  "ui/src/App.jsx:createSpecialEvent"
  "ui/src/App.jsx:maintenanceModeForm"
  "ui/src/App.jsx:enableMaintenanceMode"
  "ui/src/App.jsx:floorName"
  "ui/src/App.jsx:roomName"
  "node-api/server.js:buildZonePath"
  "ui/src/App.jsx:AdminPage"
  "ui/src/App.jsx:AutonomousModePanel"
  "ui/src/App.jsx:DeviceProvisioningPanel"
  "ui/src/App.jsx:ZoneDeviceBrowser"
  "ui/src/App.jsx:DeviceDetailsPanel"
  "ui/src/App.jsx:Device Persistent Storage and Setpoint Retention"
  "ui/src/App.jsx:Enable device persistent storage"
  "ui/src/App.jsx:persistentStorageMedium"
  "ui/src/App.jsx:setpointStorage"
  "ui/src/App.jsx:Battery Percent"
  "ui/src/App.jsx:\"schedule\", \"range\", \"calibration\", \"counters\""
  "ui/src/App.jsx:Persist BACnet schedules on device"
  "ui/src/App.jsx:EnergyUsageCharts"
  "ui/src/App.jsx:ReportingCenter"
  "ui/src/App.jsx:ReportHeatMap"
  "ui/src/App.jsx:/api/reports/heat-map"
  "ui/src/App.jsx:/api/reports/schedules/run-due"
  "ui/src/App.jsx:/api/reports/schedule-runs"
  "ui/src/App.jsx:CSV"
  "ui/src/App.jsx:TelemetryFeed"
  "ui/src/App.jsx:RealTimeMonitoringPanel"
  "ui/src/App.jsx:EventDrivenArchitecturePanel"
  "ui/src/App.jsx:Event-Driven Architecture"
  "ui/src/App.jsx:EdgePlatformCapabilitiesPanel"
  "ui/src/App.jsx:BACnet Edge Platform"
  "ui/src/App.jsx:nrf52840_bacnet_devices"
  "ui/src/App.jsx:field_selectable_power_meter"
  "ui/src/App.jsx:telemetryConnected"
  "ui/src/App.jsx:EcoStruxureStyleMock"
  "ui/src/App.jsx:System Tree"
  "ui/src/App.jsx:smartGridAi"
  "ui/src/App.jsx:Trend Logging"
  "ui/src/App.jsx:AiControlPanel"
  "ui/src/App.jsx:ReinforcementLearningPanel"
  "ui/src/App.jsx:MiniBarChart"
  "ui/src/App.jsx:ResponsiveContainer"
  "ui/src/App.jsx:LineChart"
  "ui/src/App.jsx:Energy Usage Graphs"
  "ui/src/App.jsx:Live Device Values"
  "ui/src/App.jsx:Fault Detection"
  "ui/src/App.jsx:Maintenance Tickets"
  "ui/src/App.jsx:Alarm Logs"
  "ui/src/App.jsx:alarmLogs"
  "ui/src/App.jsx:EventSource"
  "node-api/eventBus.js:Kafka"
  "node-api/eventBus.js:mqtt.connect"
  "node-api/eventBus.js:mqtt_tls"
  "node-api/eventBus.js:amqp.connect"
  "node-api/eventBus.js:rabbitmq_amqp"
  "docker/docker-compose.yml:kafka:"
  "docker/docker-compose.yml:rabbitmq:"
  "docker/docker-compose.yml:MQTT_BROKER_URL"
  "docker/docker-compose.yml:KAFKA_BROKERS"
  "docker/docker-compose.yml:RABBITMQ_URL"
  "docker/docker-compose.yml:prometheus"
  "docker/docker-compose.yml:grafana"
  "docker/docker-compose.yml:alertmanager"
  "docker/docker-compose.yml:watchtower"
  "docker/docker-compose.yml:elasticsearch"
  "docker/docker-compose.yml:logstash"
  "docker/docker-compose.yml:kibana"
  ".github/workflows/cd.yml:canary_percent"
  ".github/workflows/cd.yml:deploy-primary-canary"
  "scripts/deploy_canary.sh:CANARY_PERCENT"
  "docs/product-overview.md:Go-To-Market"
  "docs/product-overview.md:Multi-tenant"
  "docs/product-overview.md:Publish-Ready Architecture Diagram"
  "docs/demo-environment.md:IntelliBuild Energy Demo Environment"
  "docs/demo-environment.md:http://localhost:5173"
  "docs/bacnet-135-2020-conformance.md:ANSI/ASHRAE Standard 135-2020"
  "docs/bacnet-135-2020-conformance.md:ReadProperty"
  "docs/bacnet-135-2020-conformance.md:WriteProperty"
  "docs/bacnet-135-2020-conformance.md:SubscribeCOV"
  "docs/bacnet-135-2020-conformance.md:ReadPropertyMultiple"
  "docs/bacnet-135-2020-conformance.md:ConfirmedCOVNotification"
  "docs/bacnet-135-2020-conformance.md:UnconfirmedCOVNotification"
  "docs/bacnet-135-2020-conformance.md:Device-scoped schedules are mirrored"
  "docs/bacnet-135-2020-conformance.md:Energy Services Interface"
  "docs/bacnet-135-2020-conformance.md:B/WS"
  "docs/bacnet-135-2020-conformance.md:sourceforge.net/projects/bacnet"
  "docs/bacnet-135-2020-conformance.md:PICS"
  "docs/bacnet-ecostruxure-system-diagram.md:React WebStation-Style UI"
  "docs/bacnet-ecostruxure-system-diagram.md:SubscribeCOV"
  "docs/architecture.md:MQTT over TLS"
  "docs/architecture.md:RabbitMQ AMQP"
  "docs/architecture.md:RabbitMQ AMQP is the default edge command queue"
  "docs/architecture.md:EDGE_COMMAND_TRANSPORT=rabbitmq"
  "docs/architecture.md:bems.edge.commands"
  "docs/architecture.md:Event-Driven Runtime"
  "docs/architecture.md:Kafka is the local/backend event bus"
  "docs/architecture.md:nRF52840 BACnet field devices"
  "docs/architecture.md:BLE, Thread, or IEEE 802.15.4"
  "docs/architecture.md:5-in-1 power meter profile"
  "docs/architecture.md:one configurable pulse output"
  "docs/architecture.md:two configurable pulse inputs"
  "docs/architecture.md:Device EEPROM configuration"
  "docs/architecture.md:retained setpoint storage"
  "docs/architecture.md:device persistent storage"
  "docs/architecture.md:device-resident BACnet schedule storage"
  "docs/architecture.md:field-device/"
  "docs/architecture.md:Implemented BACnet extension surfaces"
  "docs/architecture.md:ReadPropertyMultiple"
  "docs/architecture.md:ConfirmedCOVNotification/UnconfirmedCOVNotification"
  "docs/architecture.md:implemented EIA-485 BACnet MS/TP serial adapter"
  "docs/architecture.md:GET /api/bacnet/object-map"
  "docs/architecture.md:GET /api/bacnet/equipment-map"
  "docs/architecture.md:GET /api/reports/summary"
  "docs/architecture.md:GET /api/reports/heat-map"
  "docs/architecture.md:scheduled report delivery"
  "docs/architecture.md:due-run"
  "docs/architecture.md:OTA_PRIVATE_KEY_PEM"
  "docs/architecture.md:reports:view"
  "docs/api-surface.md:GET /api/reports/trends.csv"
  "docs/api-surface.md:GET /api/bacnet/object-map"
  "docs/api-surface.md:GET /api/edge/command-transport"
  "docs/api-surface.md:EDGE_COMMAND_TRANSPORT=rabbitmq"
  "docs/api-surface.md:ReadPropertyMultiple batch reads"
  "docs/api-surface.md:POST /api/edge/cov-notifications"
  "docs/api-surface.md:GET /api/bacnet/vendor-metadata"
  "docs/api-surface.md:POST /api/bacnet/mstp/read"
  "docs/api-surface.md:EIA-485 serial adapter"
  "docs/api-surface.md:GET /api/reports/heat-map"
  "docs/api-surface.md:POST /api/reports/schedules/run-due"
  "docs/api-surface.md:reports:export"
  "docs/architecture.md:battery percentage"
  "docs/architecture.md:OTA update orchestration"
  "docs/architecture.md:Device architecture traceability"
  "docs/architecture.md:bacnet_bare_metal_field_devices"
  "docs/architecture.md:/api/devices/:deviceId/ota-update"
  "docs/architecture.md:docs/device-architecture.md"
  "docs/architecture.md:field-device/include/field_device_firmware.h"
  "docs/architecture.md:POST /api/firmware/artifacts"
  "docs/device-architecture.md:Device Persistent Storage"
  "docs/device-architecture.md:BACnet Schedule object persistence on the device"
  "docs/device-architecture.md:battery percentage"
  "docs/device-architecture.md:OTA Update"
  "docs/device-architecture.md:BACnet bare-metal field devices"
  "docs/device-architecture.md:bare metal scheduler"
  "docs/device-architecture.md:C++ Design Patterns and SOLID Principles"
  "docs/device-architecture.md:IControlStrategy"
  "docs/device-architecture.md:Dependency inversion"
  "docs/device-architecture.md:field-device/CMakeLists.txt"
  "docs/device-architecture.md:Signed firmware metadata"
  "docs/device-architecture.md:GET /api/firmware/ota-jobs"
  "docs/device-architecture.md:nRF52840 BACnet Devices"
  "docs/device-architecture.md:Flash NVS"
  "docs/device-architecture.md:Field-Selectable Power Meters"
  "docs/device-architecture.md:5-in-1 field-selectable communication profile"
  "docs/device-architecture.md:RabbitMQ"
  "field-device/include/field_device_firmware.h:class IBacnetObjectTable"
  "field-device/include/field_device_firmware.h:class IPersistentStore"
  "field-device/include/field_device_firmware.h:class IScheduleRepository"
  "field-device/include/field_device_firmware.h:class IOtaUpdater"
  "field-device/include/field_device_firmware.h:class ISignatureVerifier"
  "field-device/include/field_device_firmware.h:class ITransportPort"
  "field-device/include/field_device_firmware.h:class BareMetalFieldDeviceApplication"
  "field-device/src/simulated_drivers.cpp:SimulatedFlashStore"
  "field-device/src/simulated_drivers.cpp:SignedBootloaderOtaUpdater"
  "field-device/tests/field_device_simulator_test.cpp:SimulatedRadioTransport"
  "field-device/CMakeLists.txt:field_device_simulator_test"
  "field-device/README.md:SOLID"
  "field-device/README.md:Strategy"
  "docs/architecture.md:Azure IoT Hub"
  "docs/architecture.md:AWS IoT Core"
  "docs/architecture.md:Node-RED"
  "docs/architecture.md:Sedona"
  "docs/bems-backend-design.md:Designing Your Own BEMS Backend"
  "docs/bems-backend-design.md:Server-Sent Events"
  "docs/bems-backend-design.md:Smart Grid AI Design"
  "docs/bems-backend-design.md:Real-Time Monitoring Design"
  "docs/database-schema.md:BMS/BEMS Database Schema Design"
  "docs/database-schema.md:Trend logging"
)

for check in "${checks[@]}"; do
  file="${check%%:*}"
  pattern="${check#*:}"
  grep -q "$pattern" "$file" || {
    echo "Architecture marker not found: $pattern in $file" >&2
    exit 1
  }
done

if grep -R -n -E "new WebSocket|socket\\.io|ws://" docs node-api ui/src docker database edge-core --exclude-dir=node_modules --exclude-dir=dist; then
  echo "WebSocket implementation marker found; architecture requires SSE instead." >&2
  exit 1
fi

if grep -R -n -E "FreeRTOS|RTOS|rtosRequired|firmwareProfile" docs node-api ui/src docker database edge-core field-device --exclude-dir=node_modules --exclude-dir=dist; then
  echo "RTOS marker found; device architecture requires BACnet bare-metal field devices." >&2
  exit 1
fi

if grep -R -n -E "Planned BACnet extensions|not yet complete|future serial adapter|Reporting foundations|configured fieldbus gateway adapter" docs/architecture.md docs/api-surface.md docs/device-architecture.md; then
  echo "Architecture drift marker found; docs must describe implemented surfaces." >&2
  exit 1
fi

node --check node-api/server.js >/dev/null
node --check node-api/auth.js >/dev/null
node --check node-api/aiClient.js >/dev/null
node --check node-api/edgeClient.js >/dev/null
node --check node-api/migrations/runMigrations.js >/dev/null
python3 -m py_compile ai-service/app.py

echo "Architecture verification passed."
