BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"

BBFILE_COLLECTIONS += "bems"
BBFILE_PATTERN_bems = "^${LAYERDIR}/"
BBFILE_PRIORITY_bems = "6"

LAYERSERIES_COMPAT_bems = "nanbield scarthgap styhead"
